-- Dữ liệu hồ sơ, cài đặt, từ khóa và chuyên mục được tạo bởi trigger public.handle_new_user.
-- Migration 202607090001_verified_default_sources.sql bổ sung 9 nguồn RSS đã kiểm tra,
-- bật sẵn cho tài khoản hiện có và tài khoản tạo mới, không tạo bản trùng.
