services:
  - type: web
    name: tin-nhanh-ca-nhan
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://qjpcxhackvoewcxlatis.supabase.co
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_TArSkv7lbokFpK9KZxp5Iw_iJ7f29wh
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
