const TRACKING=new Set(['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid','ref','source','campaign']);
const STOPWORDS=new Set(['va','la','cua','co','cho','trong','voi','duoc','tai','mot','nhung','cac','khi','da','se','ve','theo','nay','den','tren','sau','truoc','do','bi','dang','ra','lai','nhieu','them']);
const PREFIXES=['tin moi','tin nong','moi nhat','cap nhat','video','anh','truc tiep','breaking news'];
export function stripHtml(value:string):string{return value.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&(amp|lt|gt|quot|#39|nbsp);/gi,(m)=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#39;':"'",'&nbsp;':' '}[m.toLowerCase()]??' ')).replace(/&#(\d+);/g,(_,c)=>String.fromCodePoint(Number(c))).replace(/\s+/g,' ').trim();}
export function normalize(value:string):string{return stripHtml(value).normalize('NFKC').toLowerCase().replace(/đ/g,'d').normalize('NFD').replace(/\p{M}/gu,'').replace(/\p{Extended_Pictographic}/gu,' ').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();}
export function tokenize(value:string,removeStop=true):string[]{return normalize(value).split(' ').filter((x)=>x.length>1&&(!removeStop||!STOPWORDS.has(x)));}
export function normalizeTitle(value:string):string{let out=normalize(value);let changed=true;while(changed){changed=false;for(const p of PREFIXES){if(out===p||out.startsWith(`${p} `)){out=out.slice(p.length).trim();changed=true;}}}return tokenize(out,true).join(' ');}
export function canonicalizeUrl(input:string):string{const u=new URL(input.trim());u.hash='';u.hostname=u.hostname.toLowerCase().replace(/^www\./,'');u.pathname=u.pathname.replace(/\/$/,'')||'/';const entries=[...u.searchParams.entries()].filter(([k])=>!TRACKING.has(k.toLowerCase())).sort(([a,av],[b,bv])=>a.localeCompare(b)||av.localeCompare(bv));u.search='';for(const [k,v] of entries)u.searchParams.append(k,v);return u.toString().replace(/\/$/,'');}
export async function sha256(value:string):Promise<string>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map((x)=>x.toString(16).padStart(2,'0')).join('');}
function fnv(value:string):bigint{let h=0xcbf29ce484222325n;for(const b of new TextEncoder().encode(value)){h^=BigInt(b);h=BigInt.asUintN(64,h*0x100000001b3n);}return h;}
export function simhash(value:string):string{const vector=Array<number>(64).fill(0);for(const term of tokenize(value,false)){const h=fnv(term);for(let i=0;i<64;i++)vector[i]=(vector[i]??0)+(((h>>BigInt(i))&1n)===1n?1:-1);}let out=0n;for(let i=0;i<64;i++)if((vector[i]??0)>=0)out|=1n<<BigInt(i);return BigInt.asUintN(64,out).toString(16).padStart(16,'0');}
function hamming(a:string,b:string):number{let v=BigInt(`0x${a}`)^BigInt(`0x${b}`);let n=0;while(v){n+=Number(v&1n);v>>=1n;}return n;}
function jaccard(a:string,b:string):number{const x=new Set(tokenize(a));const y=new Set(tokenize(b));const inter=[...x].filter((t)=>y.has(t)).length;return inter/new Set([...x,...y]).size||0;}
function ngrams(v:string):Map<string,number>{const text=` ${v.replace(/\s+/g,' ').trim()} `;const m=new Map<string,number>();for(let i=0;i<=text.length-3;i++){const g=text.slice(i,i+3);m.set(g,(m.get(g)??0)+1);}return m;}
function cosine(a:string,b:string):number{const x=ngrams(a),y=ngrams(b);let dot=0,nx=0,ny=0;for(const v of x.values())nx+=v*v;for(const v of y.values())ny+=v*v;for(const [k,v] of x)dot+=v*(y.get(k)??0);return nx&&ny?dot/Math.sqrt(nx*ny):0;}
export interface Candidate{guid:string|null;source_id:string;canonical_url:string;url_hash:string;normalized_title:string;title_hash:string;simhash:string;published_at:string;}
export function duplicateDecision(a:Candidate,b:Candidate):boolean{const hours=Math.abs(new Date(a.published_at).getTime()-new Date(b.published_at).getTime())/3_600_000;if(a.guid&&b.guid&&a.source_id===b.source_id&&a.guid===b.guid)return true;if(a.url_hash===b.url_hash||a.canonical_url===b.canonical_url)return true;if(a.normalized_title===b.normalized_title&&hours<=168)return true;const jac=jaccard(a.normalized_title,b.normalized_title),cos=cosine(a.normalized_title,b.normalized_title),ham=hamming(a.simhash,b.simhash),meaningful=Math.min(new Set(tokenize(a.normalized_title)).size,new Set(tokenize(b.normalized_title)).size);return hours<=72&&((ham<=3&&jac>=.82&&meaningful>=5)||(jac>=.90&&meaningful>=5)||(cos>=.92&&hours<=24));}
export interface Rule{keyword:string;rule_type:'positive'|'negative'|'required';target_field:'title'|'description'|'all';weight:number;enabled:boolean;}
export function halfLife(category:string):number{const n=normalize(category);if(/thue|ke toan|phap luat|hoa don|bao hiem/.test(n))return 120;if(/cong nghe|ai|tu dong hoa|excel|vba|python/.test(n))return 72;if(/huong dan|ky nang|giao duc/.test(n))return 240;return 24;}
export function scoreArticle(input:{title:string;description:string;category:string;sourcePriority:number;publishedAt:string;imageUrl:string|null;author:string|null;url:string;categoryWeight:number;rules:Rule[]}){const title=normalize(input.title),description=normalize(input.description);let positive=0,negative=0,hidden=false;const matched=new Set<string>();for(const rule of input.rules.filter(r=>r.enabled)){const k=normalize(rule.keyword),it=rule.target_field!=='description'&&title.includes(k),id=rule.target_field!=='title'&&description.includes(k);if(!it&&!id){if(rule.rule_type==='required')hidden=true;continue;}matched.add(rule.keyword);const bonus=rule.keyword.includes(' ')?1.2:1;if(rule.rule_type!=='negative')positive+=((it?rule.weight*3:0)+(id?rule.weight:0))*bonus;else{if(rule.weight>=100)hidden=true;negative+=(it?rule.weight*5:0)+(id?rule.weight*2:0);}}const category=Math.max(0,Math.min(25,input.categoryWeight/10*25)),source=Math.max(0,Math.min(15,input.sourcePriority/10*15)),age=Math.max(0,(Date.now()-new Date(input.publishedAt).getTime())/3_600_000),freshness=20*Math.exp(-age/halfLife(input.category));let quality=0;if(input.imageUrl)quality+=2;if(input.description.length>100)quality+=2;if(!Number.isNaN(new Date(input.publishedAt).getTime()))quality+=2;if(input.author)quality+=1;if(input.url.startsWith('https:'))quality+=1;if(!/(sốc|kinh hoàng|không thể tin|giật mình|chấn động)/i.test(input.title))quality+=2;const total=hidden?0:Math.max(0,Math.min(100,category+Math.min(30,positive)+source+freshness+quality-negative));return{total,hidden,matchedKeywords:[...matched],breakdown:{category,keywords:Math.min(30,positive),source,freshness,quality,negative,total}};}
export function representativeScore(input:{priority:number;image:boolean;descriptionLength:number;publishedAt:string;author:boolean},earliest?:string):number{const early=earliest?Math.max(0,15-Math.min(15,Math.max(0,(new Date(input.publishedAt).getTime()-new Date(earliest).getTime())/3_600_000))):15;return 30*(Math.max(0,Math.min(10,input.priority))/10)+(input.image?20:0)+Math.min(20,input.descriptionLength/20)+early+10+(input.author?5:0);}
