import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '../services/supabase';
import type { CategoryPreference, KeywordRule } from '../types/domain';
import { useAuth } from '../hooks/useAuth';
import { errorMessage } from '../utils/error';

export function RulesPage(){
  const {user}=useAuth(); const client=useQueryClient(); const [keyword,setKeyword]=useState(''); const [type,setType]=useState<KeywordRule['rule_type']>('positive'); const [weight,setWeight]=useState(3); const [message,setMessage]=useState('');
  const rules=useQuery({queryKey:['rules'],queryFn:async()=>{const {data,error}=await supabase.from('keyword_rules').select('*').order('rule_type').order('keyword');if(error)throw error;return data??[];}});
  const categories=useQuery({queryKey:['categories'],queryFn:async()=>{const {data,error}=await supabase.from('category_preferences').select('*').order('weight',{ascending:false});if(error)throw error;return data??[];}});
  async function add(){if(!user||!keyword.trim())return;const {error}=await supabase.from('keyword_rules').insert({user_id:user.id,keyword:keyword.trim(),rule_type:type,target_field:'all',weight,enabled:true});if(error)setMessage(error.message);else{setKeyword('');await client.invalidateQueries({queryKey:['rules']});}}
  async function patchRule(id:string,patch:Partial<KeywordRule>){const {error}=await supabase.from('keyword_rules').update(patch).eq('id',id);if(error)setMessage(error.message);else await client.invalidateQueries({queryKey:['rules']});}
  async function patchCategory(id:string,patch:Partial<CategoryPreference>){const {error}=await supabase.from('category_preferences').update(patch).eq('id',id);if(error)setMessage(error.message);else await client.invalidateQueries({queryKey:['categories']});}
  return <div className="stack-page"><section className="page-heading"><div><h1>Sở thích và từ khóa</h1><p>Điều chỉnh quy tắc chấm điểm minh bạch, không dùng mô hình AI.</p></div></section>{message&&<div className="notice">{message}</div>}
    <section className="panel"><h2>Thêm từ khóa</h2><div className="rule-add"><input placeholder="Ví dụ: hóa đơn điện tử" value={keyword} onChange={(e)=>setKeyword(e.target.value)}/><select value={type} onChange={(e)=>setType(e.target.value as KeywordRule['rule_type'])}><option value="positive">Tích cực</option><option value="negative">Tiêu cực</option><option value="required">Bắt buộc</option></select><label>Trọng số {weight}<input type="range" min="1" max="10" value={weight} onChange={(e)=>setWeight(Number(e.target.value))}/></label><button className="button primary" onClick={()=>void add()}>Thêm</button></div><div className="rule-list">{rules.data?.map((rule)=><article key={rule.id}><input type="checkbox" checked={rule.enabled} onChange={(e)=>void patchRule(rule.id,{enabled:e.target.checked})}/><strong>{rule.keyword}</strong><span>{rule.rule_type==='positive'?'Tăng điểm':rule.rule_type==='negative'?'Giảm điểm':'Bắt buộc'}</span><select value={rule.target_field} onChange={(e)=>void patchRule(rule.id,{target_field:e.target.value as KeywordRule['target_field']})}><option value="all">Tiêu đề + mô tả</option><option value="title">Tiêu đề</option><option value="description">Mô tả</option></select><input className="small-number" type="number" min="1" max="100" value={rule.weight} onChange={(e)=>void patchRule(rule.id,{weight:Number(e.target.value)})}/><button className="danger-link" onClick={async()=>{const {error}=await supabase.from('keyword_rules').delete().eq('id',rule.id);if(error)setMessage(errorMessage(error));else await client.invalidateQueries({queryKey:['rules']});}}>Xóa</button></article>)}</div></section>
    <section className="panel"><h2>Trọng số chuyên mục</h2><div className="category-list">{categories.data?.map((category)=><article key={category.id}><label className="checkbox"><input type="checkbox" checked={category.enabled} onChange={(e)=>void patchCategory(category.id,{enabled:e.target.checked})}/>{category.category}</label><input type="range" min="0" max="10" value={category.weight} onChange={(e)=>void patchCategory(category.id,{weight:Number(e.target.value)})}/><strong>{category.weight}/10</strong></article>)}</div></section>
  </div>;
}
