import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '../services/supabase';
import type { UserSettings } from '../types/domain';
import { useAuth } from '../hooks/useAuth';
import { errorMessage } from '../utils/error';
export function SettingsPage(){
  const {user}=useAuth(); const query=useQuery({queryKey:['settings'],queryFn:async()=>{const {data,error}=await supabase.from('user_settings').select('*').single();if(error)throw error;return data;}}); const [settings,setSettings]=useState<UserSettings|null>(null); const [message,setMessage]=useState('');
  useEffect(()=>{if(query.data)setSettings(query.data);},[query.data]);
  async function save(){if(!user||!settings)return;const {error}=await supabase.from('user_settings').upsert({...settings,user_id:user.id});setMessage(error?errorMessage(error):'Đã lưu cài đặt.');}
  if(!settings)return <div className="center-screen">Đang tải cài đặt…</div>;
  return <div className="stack-page"><section className="page-heading"><div><h1>Cài đặt</h1><p>Các thông số ảnh hưởng đến phân trang, thời gian lưu và hiển thị.</p></div></section><section className="panel settings-form"><label>Số bài mỗi trang<select value={settings.page_size} onChange={(e)=>setSettings({...settings,page_size:Number(e.target.value)})}>{[10,20,30,50].map(x=><option key={x}>{x}</option>)}</select></label><label>Giữ bài trong bao nhiêu ngày<input type="number" min="7" max="365" value={settings.article_retention_days} onChange={(e)=>setSettings({...settings,article_retention_days:Number(e.target.value)})}/></label><label>Khoảng quét mong muốn (phút)<input type="number" min="15" max="1440" value={settings.scan_interval_minutes} onChange={(e)=>setSettings({...settings,scan_interval_minutes:Number(e.target.value)})}/></label><label>Sắp xếp mặc định<select value={settings.default_sort} onChange={(e)=>setSettings({...settings,default_sort:e.target.value as UserSettings['default_sort']})}><option value="relevance">Phù hợp nhất</option><option value="newest">Mới nhất</option></select></label><label>Ảnh dự phòng<select value={settings.image_fallback_mode} onChange={(e)=>setSettings({...settings,image_fallback_mode:e.target.value as UserSettings['image_fallback_mode']})}><option value="logo">Logo nguồn</option><option value="category">Ảnh chuyên mục</option></select></label><label className="checkbox"><input type="checkbox" checked={settings.show_hidden} onChange={(e)=>setSettings({...settings,show_hidden:e.target.checked})}/>Cho phép xem tin đã ẩn</label><button className="button primary" onClick={()=>void save()}>Lưu cài đặt</button>{message&&<p className="form-message">{message}</p>}</section><section className="panel"><h2>Phím tắt trên laptop</h2><p>←/→ đổi trang hoặc bài; S lưu bài; R đánh dấu đã đọc; Esc quay lại.</p></section></div>;
}
