import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { deleteSource, listCatalog, listSources, saveSource } from '../services/sources';
import { discoverFeed, scanSource, validateFeed } from '../services/functions';
import type { FeedValidationResult, Source } from '../types/domain';
import { errorMessage } from '../utils/error';
import { formatDateTime } from '../utils/date';

const EMPTY = { name:'', feed_url:'', website_url:'', logo_url:'', category:'Tin tổng hợp', priority:5, enabled:true };
export function SourcesPage() {
  const client=useQueryClient(); const sources=useQuery({queryKey:['sources'],queryFn:listSources}); const catalog=useQuery({queryKey:['catalog'],queryFn:listCatalog});
  const [form,setForm]=useState(EMPTY); const [editingId,setEditingId]=useState<string|null>(null); const [result,setResult]=useState<FeedValidationResult|null>(null); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const refresh=()=>client.invalidateQueries({queryKey:['sources']});
  const save=useMutation({mutationFn:()=>saveSource({...form,id:editingId??undefined} as Partial<Source>&Pick<Source,'name'|'feed_url'|'category'>),onSuccess:async()=>{setMessage('Đã lưu nguồn.');setForm(EMPTY);setEditingId(null);setResult(null);await refresh();},onError:(e)=>setMessage(errorMessage(e))});
  async function check(url=form.feed_url){ setBusy(true);setMessage('');try{const data=await validateFeed(url);setResult(data);if(!form.name)setForm((x)=>({...x,name:data.feedName,website_url:data.websiteUrl??x.website_url}));}catch(e){setResult(null);setMessage(errorMessage(e));}finally{setBusy(false);} }
  async function discover(){setBusy(true);setMessage('');try{const data=await discoverFeed(form.feed_url);if(!data.feeds.length)throw new Error('Không tìm thấy RSS trên website này.');const first=data.feeds[0];if(!first) return;setForm((x)=>({...x,feed_url:first.url,name:x.name||first.feedName,website_url:first.websiteUrl??x.website_url}));setResult(first);setMessage(data.feeds.length>1?`Tìm thấy ${data.feeds.length} feed; đã chọn feed đầu tiên. Hãy kiểm tra lại trước khi lưu.`:'Đã tìm thấy RSS.');}catch(e){setMessage(errorMessage(e));}finally{setBusy(false);} }
  function edit(source:Source){setEditingId(source.id);setForm({name:source.name,feed_url:source.feed_url,website_url:source.website_url??'',logo_url:source.logo_url??'',category:source.category,priority:source.priority,enabled:source.enabled});setResult(null);window.scrollTo({top:0,behavior:'smooth'});}
  async function submit(e:FormEvent){e.preventDefault();if(!result?.valid){setMessage('Phải bấm “Kiểm tra RSS” và nhận kết quả hợp lệ trước khi lưu.');return;}await save.mutateAsync();}
  async function addCatalog(feedUrl:string,name:string,category:string,priority:number){setForm({...EMPTY,feed_url:feedUrl,name,category,priority});setEditingId(null);setResult(null);window.scrollTo({top:0,behavior:'smooth'});await check(feedUrl);}
  return <div className="stack-page"><section className="page-heading"><div><h1>Nguồn tin RSS</h1><p>Thêm URL RSS hoặc dán địa chỉ website để hệ thống tìm feed.</p></div><button onClick={()=>void scanSource().then(()=>{setMessage('Đã yêu cầu quét toàn bộ nguồn.');return refresh();}).catch((e)=>setMessage(errorMessage(e)))}>Quét toàn bộ</button></section>
    <section className="panel"><h2>{editingId?'Sửa nguồn':'Thêm nguồn'}</h2><form className="source-form" onSubmit={submit}><label>URL RSS hoặc website<input type="url" required value={form.feed_url} onChange={(e)=>{setForm({...form,feed_url:e.target.value});setResult(null);}} placeholder="https://.../rss/..."/></label><div className="inline-actions"><button type="button" disabled={busy||!form.feed_url} onClick={()=>void check()}>{busy?'Đang kiểm tra…':'Kiểm tra RSS'}</button><button type="button" disabled={busy||!form.feed_url} onClick={()=>void discover()}>Tìm RSS từ website</button></div><label>Tên nguồn<input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label>Website gốc<input type="url" value={form.website_url} onChange={(e)=>setForm({...form,website_url:e.target.value})}/></label><label>Logo URL<input type="url" value={form.logo_url} onChange={(e)=>setForm({...form,logo_url:e.target.value})}/></label><div className="form-grid"><label>Chuyên mục<input value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})}/></label><label>Ưu tiên: {form.priority}<input type="range" min="1" max="10" value={form.priority} onChange={(e)=>setForm({...form,priority:Number(e.target.value)})}/></label><label className="checkbox"><input type="checkbox" checked={form.enabled} onChange={(e)=>setForm({...form,enabled:e.target.checked})}/> Bật nguồn</label></div>{result&&<div className="validation-result"><strong>RSS hợp lệ</strong><span>{result.feedName} • {result.format} • đọc thử {result.itemCount} bài</span><span>Bài mới nhất: {formatDateTime(result.newestDate)} • {result.hasImage?'Có ảnh':'Chưa thấy ảnh'}</span></div>}<div className="inline-actions"><button className="button primary" disabled={save.isPending}>{save.isPending?'Đang lưu…':'Lưu nguồn'}</button>{editingId&&<button type="button" onClick={()=>{setEditingId(null);setForm(EMPTY);setResult(null);}}>Hủy sửa</button>}</div>{message&&<p className="form-message">{message}</p>}</form></section>
    <section className="panel"><h2>Nguồn của tôi</h2>{sources.isLoading?<p>Đang tải…</p>:!sources.data?.length?<p>Chưa có nguồn nào.</p>:<div className="source-list">{sources.data.map((source)=><article className="source-row" key={source.id}><div><strong>{source.name}</strong><small>{source.feed_url}</small><span>{source.category} • Ưu tiên {source.priority} • {source.enabled?'Đang bật':'Đang tắt'}</span><span>Lần quét: {formatDateTime(source.last_scanned_at)} • {source.last_status??'chưa quét'}{source.last_error?` • ${source.last_error}`:''}</span></div><div className="row-actions"><button onClick={()=>void scanSource(source.id).then(()=>{setMessage(`Đã quét ${source.name}.`);return refresh();}).catch((e)=>setMessage(errorMessage(e)))}>Quét ngay</button><button onClick={()=>edit(source)}>Sửa</button><button className="danger-link" onClick={()=>{if(confirm(`Xóa nguồn ${source.name}?`))void deleteSource(source.id).then(refresh).catch((e)=>setMessage(errorMessage(e)));}}>Xóa</button></div></article>)}</div>}</section>
    <section className="panel"><h2>Danh mục nguồn gợi ý</h2><p className="muted">URL có thể thay đổi theo từng báo. Mỗi nguồn luôn được kiểm tra thực tế trước khi thêm vào tài khoản.</p><div className="catalog-grid">{catalog.data?.map((item)=><article key={item.id}><strong>{item.name}</strong><span>{item.category}</span><small>{item.feed_url}</small><span className={item.verification_status==='verified'?'status-ok':'status-warn'}>{item.verification_status==='verified'?'Đã xác nhận':'Cần kiểm tra lúc thêm'}</span><button onClick={()=>void addCatalog(item.feed_url,item.name,item.category,item.priority)}>Kiểm tra & thêm</button></article>)}</div></section>
  </div>;
}
